# Generated by Django 3.0.7 on 2020-06-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='fasten_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoetype',
            name='style',
            field=models.CharField(choices=[('Sneaker', 'Sneaker'), ('Wedges', 'Wedges'), ('Boot', 'Boot'), ('Sandal', 'Sandal'), ('Dress', 'Dress'), ('Other', 'Other')], default='Sneaker', max_length=7),
        ),
    ]
